/**
 * Sound-design map. One line per cue: the frame the VISUAL lands on, the sample
 * (public/sfx, generated by `npm run sfx`) and its level. Cues are fired 2
 * frames early by <Sound/> so they feel locked to the picture.
 * The piece is designed to work in silence: the sound only underlines it.
 */
export type Cue = { f: number; sfx: string; vol: number; note?: string };

export const BED = { file: "bed", vol: 0.3 };

export const CUES: Cue[] = [
  // 01 · conversación
  { f: 36, sfx: "tick", vol: 0.35, note: "client appears" },
  { f: 56, sfx: "tock", vol: 0.3, note: "mediator appears" },
  { f: 126, sfx: "ping-a", vol: 0.34, note: "'conversación' — the floor answers" },
  // 02 · tres actores
  { f: 236, sfx: "whoosh", vol: 0.22, note: "travelling right" },
  { f: 280, sfx: "thump", vol: 0.3, note: "the insurer rises" },
  { f: 318, sfx: "ping-a", vol: 0.28, note: "cliente" },
  { f: 332, sfx: "ping-b", vol: 0.28, note: "mediador" },
  { f: 346, sfx: "ping-c", vol: 0.28, note: "aseguradora" },
  // 03 · agentes
  { f: 396, sfx: "riser", vol: 0.28, note: "the swarm gathers" },
  { f: 462, sfx: "chime", vol: 0.3, note: "the agent connects" },
  // 04 · comparan · cotizan · contratan
  { f: 558, sfx: "whoosh", vol: 0.3, note: "stream leaves the system" },
  { f: 598, sfx: "scan", vol: 0.3, note: "compare sweep" },
  { f: 640, sfx: "tick", vol: 0.3, note: "filtered" },
  { f: 664, sfx: "tick", vol: 0.25 },
  { f: 676, sfx: "tick", vol: 0.25 },
  { f: 688, sfx: "tick", vol: 0.25 },
  { f: 698, sfx: "ping-c", vol: 0.3, note: "quote produced" },
  { f: 724, sfx: "whoosh", vol: 0.25 },
  { f: 770, sfx: "seal", vol: 0.42, note: "contract sealed" },
  // 05 · Agent Economy
  { f: 806, sfx: "whoosh-long", vol: 0.3, note: "pull-out" },
  { f: 856, sfx: "swell", vol: 0.32, note: "the name" },
  // 06 · reglas por escribir
  { f: 1018, sfx: "tock", vol: 0.34, note: "¿Quién entra?" },
  { f: 1070, sfx: "tock", vol: 0.34, note: "¿Qué se intercambia?" },
  { f: 1120, sfx: "tock", vol: 0.34, note: "¿Quién cobra?" },
  // 07 · precio
  { f: 1168, sfx: "whoosh-long", vol: 0.3, note: "into the stream" },
  { f: 1240, sfx: "ping-a", vol: 0.26, note: "'precio' loses weight" },
  // 08 · criterio
  { f: 1300, sfx: "whoosh", vol: 0.22 },
  { f: 1348, sfx: "tick", vol: 0.28, note: "focus" },
  { f: 1370, sfx: "chime", vol: 0.32, note: "the one that matters" },
  // 09 · dato
  { f: 1398, sfx: "whoosh", vol: 0.2 },
  { f: 1440, sfx: "tick", vol: 0.22 },
  { f: 1456, sfx: "tick", vol: 0.22 },
  { f: 1476, sfx: "ping-b", vol: 0.28, note: "structure" },
  // 10 · confianza
  { f: 1506, sfx: "swell", vol: 0.28, note: "calm" },
  { f: 1590, sfx: "ping-a", vol: 0.24, note: "line closes" },
  // 11 · primer paso
  { f: 1650, sfx: "thump", vol: 0.36, note: "first move" },
  { f: 1670, sfx: "ping-b", vol: 0.28, note: "the floor answers" },
  { f: 1684, sfx: "tick", vol: 0.2 },
  { f: 1694, sfx: "tick", vol: 0.2 },
  { f: 1704, sfx: "tick", vol: 0.2 },
  // 12 · clímax
  { f: 1716, sfx: "riser", vol: 0.34, note: "into the climax" },
  { f: 1776, sfx: "impact", vol: 0.55, note: "'Las reglas se están escribiendo ahora.'" },
  // cierre
  { f: 1880, sfx: "whoosh-long", vol: 0.22, note: "pink contracts" },
  { f: 1922, sfx: "tick", vol: 0.22, note: "title" },
  { f: 1968, sfx: "tick", vol: 0.22, note: "date" },
  { f: 1990, sfx: "ping-a", vol: 0.2, note: "'Nuevo artículo'" },
];
